site_name: '@passwordless-id/webauthn'
site_url: https://webauthn.passwordless.id
repo_url: https://github.com/passwordless-id/webauthn
extra_css:
  - style.css
plugins:
  - search
  - mermaid2

nav:
  - Introduction: 'index.md'
  - demos.md
  - registration.md
  - authentication.md
  - verification.md
  - passkeys-faq.md

theme:
  #name: readthedocs
  name: mkdocs
  #user_color_mode_toggle: true

  #name: material
  locale: en
  logo: passkeys-logo-dark.svg
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - toc.integrate

#markdown_extensions:
#  - pymdownx.highlight:
#      anchor_linenums: true
#  - pymdownx.superfences