site_name: '@passwordless-id/webauthn'
site_url: https://webauthn.passwordless.id
repo_url: https://github.com/passwordless-id/webauthn
extra_css:
  - css/style.css
plugins:
  - search
  - mermaid2

nav:
  - Demos:
    - Basic: demos/basic.html
    - Playground: demos/playground.html
    - Authenticators: demos/authenticators.html
  - Docs:
    - docs/registration.md
    - docs/authentication.md
    - docs/verification.md
    - docs/version_1.md
  - F.A.Q.:
    - faq/passkeys-faq.md
    - faq/why_not.md

theme:
  #name: readthedocs
  name: mkdocs
  color_mode: light
  hljs_style: dark
  user_color_mode_toggle: false
  custom_dir: docs/theme

  #name: material
  locale: en
  logo: passkeys-logo-dark.svg
  #features:
  #- navigation.tabs
  #- navigation.tabs.sticky
  #- toc.integrate

#markdown_extensions:
#  - pymdownx.highlight:
#      anchor_linenums: true
#  - pymdownx.superfences